server:
  port: 8080

spring:
  #  Eureka 서버에 아래 application.name으로 서비스명을 등록
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: item-service
          #          /item-service로 시작하는 url요청이 들어올 경우
          predicates:
            - Path=/item-service/**
          #          filters의 StripPrefix=1은 첫 번째 접두어 제거
          filters:
            - StripPrefix=1
          #          lb://[Eureka에 등록된 서비스명]
          #         아래 코드 대신, http://localhost:8081로 선언하면 로드밸런싱이 아닌, 8081로 직접 연결
          uri: lb://item-service
        - id: member-service
          #          /item-service로 시작하는 url요청이 들어올 경우
          predicates:
            - Path=/member-service/**
          #          filters의 StripPrefix=1은 첫 번째 접두어 제거
          filters:
            - StripPrefix=1
          #          lb://[Eureka에 등록된 서비스명]
          #         아래 코드 대신, http://localhost:8081로 선언하면 로드밸런싱이 아닌, 8081로 직접 연결
          uri: lb://member-service
        - id: order-service
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
          uri: lb://order-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
jwt:
  expiration: 30 #30?
  secretKey: mysecret